"To get started with Dependabot version updates, you need to specify package ecosystems to update and where package manifests are located Please see documentation for configuration options
"https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
ver: 2 
update package-ecosystem: "github-actions"
"Workflow files stored in the default location of .github/workflows
  directory: "/"
   schedule: # Check for updates to GitHub Actions every weekday
   interval: "weekly"
     - package-ecosystem: "composer"
  directory: "/"
 schedule:
  # Check for updates managed by Composer once a week
  interval: "weekly"
  # Allow both direct and indirect updates for all packages
  - dependency-type: "all"
   - package-ecosystem: "pip"
   directory: "/"
  schedule:
interval: "weekly"
 allow: # Allow only direct updates for
# Django
 - dependency-name: "django*"
    dependency-type: "direct"
 # Allow only production updates for Sphinx
- dependency-name: "sphinx"
    dependency-type: "production"
    update-types:
  - "minor"
- "patch"
  # Add assignees
assignees:
  - "apetree100122"
